---
title: "Polarity Analysis of Tweets per subject"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(knitr)
library(data.table)
library(ggplot2)


# read final data
dt <- fread('../../gen/data-preparation/output/dataset.csv')
```

### Determining the number of tweets per subject

```{r}
Schools<-sum(dt$Schools, na.rm = TRUE)
Contact<-sum(dt$`Contact-Based Professions`, na.rm = TRUE)
Nursing <- sum(dt$`Nursing homes`, na.rm = TRUE)
Hospitality<-sum(dt$Hospitality, na.rm = TRUE)
Event<- sum(dt$Events, na.rm = TRUE)
Soccer<- sum(dt$`Paid Soccer`, na.rm = TRUE)
Sports<- sum(dt$Sports, na.rm = TRUE)

subjects=c("Schools", "Contact-Based Professions", "Nursing Homes", "Hospitality", "Events", "Paid Soccer", "Sports")

df <- data.frame(Subject=subjects,
                Frequency=c(Schools, Contact, Nursing,Hospitality,Event, Soccer, Sports))

kable(df, 
      caption="Number of Tweets per Subject")
```

### Graphing of number of tweets per subject
```{r}


ggplot(data=df, aes(x=Subject, y=Frequency, fill=subjects)) +
  geom_bar(stat="identity")+ ggtitle("Number of Tweets per Subject")+
  scale_fill_manual("legend", values = c("Schools"="pink", "Contact-Based Professions"="green", "Nursing Homes"= "red", "Hospitality"="purple", "Events"="yellow", "Paid Soccer"="orange", "Sports"="blue"))+
   theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank())
```

### Determining average polarity of tweets per subject
```{r}
# calculating the average sentiment per subject and assigning to value to variable
Negative.Schools <- unname((by(dt$Negative, dt$Schools, na.rm=TRUE, mean)["TRUE"]),force=FALSE)
Neutral.Schools <- unname((by(dt$Neutral, dt$Schools, na.rm=TRUE, mean)["TRUE"]), force=FALSE)
Positive.Schools <- unname((by(dt$Positive, dt$Schools,na.rm=TRUE, mean)["TRUE"]), force=FALSE)
Compound.Schools <- unname((by(dt$Compound, dt$Schools, na.rm=TRUE,mean)["TRUE"]),force=FALSE)

Negative.contact <- unname((by(dt$Negative, dt$`Contact-Based Professions`, na.rm=TRUE, mean)["TRUE"]),force=FALSE)
Neutral.contact <- unname((by(dt$Neutral, dt$`Contact-Based Professions`, na.rm=TRUE, mean)["TRUE"]), force=FALSE)
Positive.contact <- unname((by(dt$Positive, dt$`Contact-Based Professions`,na.rm=TRUE, mean)["TRUE"]), force=FALSE)
Compound.contact <- unname((by(dt$Compound, dt$`Contact-Based Professions`, na.rm=TRUE,mean)["TRUE"]),force=FALSE)

Negative.nursing <- unname((by(dt$Negative, dt$`Nursing homes`, na.rm=TRUE, mean)["TRUE"]),force=FALSE)
Neutral.nursing <- unname((by(dt$Neutral, dt$`Nursing homes`, na.rm=TRUE, mean)["TRUE"]), force=FALSE)
Positive.nursing <- unname((by(dt$Positive, dt$`Nursing homes`,na.rm=TRUE, mean)["TRUE"]), force=FALSE)
Compound.nursing <- unname((by(dt$Compound, dt$`Nursing homes`, na.rm=TRUE,mean)["TRUE"]),force=FALSE)

Negative.Hospitality <- unname((by(dt$Negative, dt$Hospitality, na.rm=TRUE, mean)["TRUE"]),force=FALSE)
Neutral.Hospitality <- unname((by(dt$Neutral, dt$Hospitality, na.rm=TRUE, mean)["TRUE"]), force=FALSE)
Positive.Hospitality <- unname((by(dt$Positive, dt$Hospitality,na.rm=TRUE, mean)["TRUE"]), force=FALSE)
Compound.Hospitality <- unname((by(dt$Compound, dt$Hospitality, na.rm=TRUE,mean)["TRUE"]),force=FALSE)

Negative.Event <- unname((by(dt$Negative, dt$Events, na.rm=TRUE, mean)["TRUE"]),force=FALSE)
Neutral.Event <- unname((by(dt$Neutral, dt$Events, na.rm=TRUE, mean)["TRUE"]), force=FALSE)
Positive.Event <- unname((by(dt$Positive, dt$Events,na.rm=TRUE, mean)["TRUE"]), force=FALSE)
Compound.Event <- unname((by(dt$Compound, dt$Events, na.rm=TRUE,mean)["TRUE"]),force=FALSE)

Negative.soccer <- unname((by(dt$Negative, dt$`Paid Soccer`, na.rm=TRUE, mean)["TRUE"]),force=FALSE)
Neutral.soccer <- unname((by(dt$Neutral, dt$`Paid Soccer`, na.rm=TRUE, mean)["TRUE"]), force=FALSE)
Positive.soccer <- unname((by(dt$Positive, dt$`Paid Soccer`,na.rm=TRUE, mean)["TRUE"]), force=FALSE)
Compound.soccer <- unname((by(dt$Compound, dt$`Paid Soccer`, na.rm=TRUE,mean)["TRUE"]),force=FALSE)

Negative.sport <- unname((by(dt$Negative, dt$Sports, na.rm=TRUE, mean)["TRUE"]),force=FALSE)
Neutral.sport <- unname((by(dt$Neutral, dt$Sports, na.rm=TRUE, mean)["TRUE"]), force=FALSE)
Positive.sport <- unname((by(dt$Positive, dt$Sports,na.rm=TRUE, mean)["TRUE"]), force=FALSE)
Compound.sport <- unname((by(dt$Compound, dt$Sports, na.rm=TRUE,mean)["TRUE"]),force=FALSE)


#creating data frames for each sentiment component

Negative<-data.frame(Subject=subjects,
                Negativity=c(Negative.Schools, Negative.contact, Negative.nursing,Negative.Hospitality,Negative.Event, Negative.soccer, Negative.sport))

kable(Negative, 
      caption="Average Proportion of Negativity in Tweets per Subject")

Positive<-data.frame(Subject=subjects,
                Positivity=c(Positive.Schools, Positive.contact, Positive.nursing,Positive.Hospitality,Positive.Event, Positive.soccer, Positive.sport))

kable(Positive, 
      caption="Average Proportion of Positivity in Tweets per Subject")

Neutral<-data.frame(Subject=subjects,
                Neutrality=c(Neutral.Schools, Neutral.contact, Neutral.nursing,Neutral.Hospitality,Neutral.Event, Neutral.soccer, Neutral.sport))

kable(Neutral, 
      caption="Average Proportion of Neutrality in Tweets per Subject")

Compound<-data.frame(Subject=subjects,
                Compound=c(Compound.Schools, Compound.contact, Compound.nursing,Compound.Hospitality,Compound.Event, Compound.soccer, Compound.sport))

kable(Compound, 
      caption="Average Compound score of Tweets per Subject")
```


### Graphing the Average Polarity of Tweets per subject
```{r}
# Hisotgram per Polarity element

ggplot(data=Negative, aes(x=Subject, y=Negativity, fill=subjects)) +
  geom_bar(stat="identity")+ ggtitle("Average Proportion of Negativity in Tweets per Subject")+
  scale_fill_manual("legend", values = c("Schools"="pink", "Contact-Based Professions"="green", "Nursing Homes"= "red", "Hospitality"="purple", "Events"="yellow", "Paid Soccer"="orange", "Sports"="blue"))+
   theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank())

ggplot(data=Positive, aes(x=Subject, y=Positivity, fill=subjects)) +
  geom_bar(stat="identity")+ ggtitle("Average Proportion of Positivity in Tweets per Subject")+
  scale_fill_manual("legend", values = c("Schools"="pink", "Contact-Based Professions"="green", "Nursing Homes"= "red", "Hospitality"="purple", "Events"="yellow", "Paid Soccer"="orange", "Sports"="blue"))+
   theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank())

ggplot(data=Neutral, aes(x=Subject, y=Neutrality, fill=subjects)) +
  geom_bar(stat="identity")+ ggtitle("Average Proportion of Negativity in Tweets per Subject")+
  scale_fill_manual("legend", values = c("Schools"="pink", "Contact-Based Professions"="green", "Nursing Homes"= "red", "Hospitality"="purple", "Events"="yellow", "Paid Soccer"="orange", "Sports"="blue"))+
   theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank())

ggplot(data=Compound, aes(x=Subject, y=Compound, fill=subjects)) +
  geom_bar(stat="identity")+ ggtitle("Average Compound score of Tweets per Subject")+
  scale_fill_manual("legend", values = c("Schools"="pink", "Contact-Based Professions"="green", "Nursing Homes"= "red", "Hospitality"="purple", "Events"="yellow", "Paid Soccer"="orange", "Sports"="blue"))+
   theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank())
```